version: '3.3'

services:
  eco-frontend:
    container_name: eco-frontend
    build:
      context: .
      dockerfile: docker/production/nginx/Dockerfile
    restart: always
    ports:
      - "3002:80"

volumes:
  app_server_data:
