version: '3.3'

services:
  eco-server:
    container_name: eco-server
    build: ../server
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - app_server_data:/usr/src/app/data

volumes:
  app_server_data:
